name: Main PR Checks
run-name: Verify `${{ github.head_ref }}` before merge to `main` by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Build: Assemble and Test desktop targets"
        run: ./gradlew desktopTest

#      - run: ./gradlew generate coverage report, upload test/coverage reports
