name: Main PR Checks
run-name: Verify `${{ github.head_ref }}` before merge to `main` by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build-app-android:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle.yml@v1
      - name: Build Android
        run: ./gradlew buildDebug buildRelease
      - name: Test Android
        run: ./gradlew test${{ inputs.android }}

  build-app-ios:
    if: github.event.pull_request.draft == false
    runs-on: macos-14
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle.yml@v1
      - name: Build iOS
        run: ./gradlew build${{ inputs.ios }}
      - name: Test iOS
        run: ./gradlew test${{ inputs.ios }}
    
  build-app-desktop:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle.yml@v1
      - name: Build Desktop
        run: ./gradlew build${{ inputs.desktop }}
      - name: Test Desktop
        run: ./gradlew test${{ inputs.desktop }}
    
  build-app-browser:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup
        uses: Pointyware/.github/.github/actions/checkout-java-gradle.yml@v1
      - name: Build Browser
        run: ./gradlew build${{ inputs.browser }}
      - name: Test Browser
        run: ./gradlew test${{ inputs.browser }}
